
[window]
option_as_alt = "Both"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.normal]
family = "Comic Code"
style = "Regular"

[general]
# live_config_reload = true
working_directory = "/Users/wontaeyang/development/projects"

import = [
    "~/.config/alacritty/themes/themes/iterm.toml"
]
